---
title: "final_project_regression"
output: pdf_document
date: "2023-09-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# Load packages
library(tidyverse)
library(tidymodels)
library(tidyselect)
library(recipes)
library(ggplot2)
#library(forecast)
#library(stacks)
library(dplyr)

```

```{r}
# Load train and test data
train <- read_csv('train.csv')
head(train)
test <- read_csv('test.csv')
head(test)
```

```{r}
# Remove `name` column from train
train <- subset(train, select = -name)
#train$x2013_code <- as_factor(train$x2013_code)
```


```{r}
code2013 <- c("one", "two", "three", "four", "five", "six")
## Create a recipe
rf_recipe_1 <- recipe(percent_dem ~ ., data = train) %>%
  step_rm(id) %>%
  step_impute_knn(all_predictors()) %>%
  step_mutate(pct_male = x0002e/x0001e) %>%
  step_mutate(pct_female = x0003e/x0001e)  %>%
  step_mutate(pct_male_18over = x0026e / x0001e) %>%
  step_mutate(pct_female_18over = x0027e / x0001e) %>%
  step_mutate(pct_21andover = x0022e/x0001e) %>%
  step_mutate(pct_62andove = x0023e/x0001e) %>%
  step_mutate(pct_female_65over = x0031e / x0001e) %>%
  step_mutate(pct_male_65over = x0030e / x0001e) %>%
  step_mutate(pct_16over = x0020e/ x0001e)%>%
  step_mutate(pct_18over = x0025e/ x0001e)%>%
  step_mutate(pct_0to19 = (x0005e + x0006e + x0007e + x0008e) / x0001e) %>%
  step_mutate(pct_20to34 = (x0009e + x0010e) / x0001e) %>%
  step_mutate(pct_35to54 = (x0011e + x0012e) / x0001e) %>%
  step_mutate(pct_55to64 = (x0013e + x0014e) / x0001e) %>%
  step_mutate(pct_65andovr = (x0015e + x0016e + x0017e) / x0001e) %>%
  step_mutate(pct_18o_citizen_m = x0088e / x0001e) %>%
  step_mutate(pct_18o_citizen_f = x0089e / x0001e) %>%
  step_mutate(pct_18o_citizen = x0087e / x0001e) %>%
  step_mutate(pct_onerace = x0034e / x0001e)  %>%
  step_mutate(pct_morerace = x0035e / x0001e) %>%
  step_mutate(pct_white = x0037e / x0001e) %>%
  step_mutate(pct_black = x0038e / x0001e) %>%
  step_mutate(pct_indian = x0039e / x0001e) %>%
  step_mutate(pct_asian = x0044e / x0001e) %>%
  step_mutate(pct_api = x0052e / x0001e) %>%
  step_mutate(pct_otherrace = x0057e / x0001e) %>%
  step_mutate(pct_white_c = x0064e / x0001e)  %>%
  step_mutate(pct_black_c = x0065e / x0001e)  %>%
  step_mutate(pct_indian_c = x0066e / x0001e)  %>%
  step_mutate(pct_asian_c = x0067e / x0001e)  %>%
  step_mutate(pct_api_c = x0068e / x0001e)  %>%
  step_mutate(pct_other_c = x0069e / x0001e)  %>%
  step_mutate(pct_his = x0071e / x0001e) %>%
  step_mutate(pct_cherokee = x0040e/x0001e) %>%
  step_mutate(pct_chippewa = x0041e/x0001e) %>%
  step_mutate(pct_navajo = x0042e/x0001e) %>%
  step_mutate(pct_sioux = x0043e/x0001e) %>%
  step_mutate(pct_indian = x0045e/x0001e) %>%
  step_mutate(pct_chinese = x0046e/x0001e) %>%
  step_mutate(pct_filipino = x0047e/x0001e) %>%
  step_mutate(pct_japanese = x0048e/x0001e) %>%
  step_mutate(pct_korean = x0049e/x0001e) %>%
  step_mutate(pct_viet = x0050e/x0001e) %>%
  step_mutate(pct_othera = x0051e/x0001e) %>%
  step_mutate(pct_hawaii = x0053e/x0001e) %>%
  step_mutate(pct_chamorro = x0054e/x0001e) %>%
  step_mutate(pct_samoan = x0055e/x0001e) %>%
  step_mutate(pct_otherpi = x0056e/x0001e) %>%
  step_mutate(pct_mexican = x0072e/x0001e) %>%
  step_mutate(pct_puertorican = x0073e/x0001e) %>%
  step_mutate(pct_cuban = x0074e/x0001e) %>%
  step_mutate(pct_otherh = x0075e/x0001e) %>%
  step_mutate(pct_whiteandblack = x0059e/x0001e) %>%
  step_mutate(pct_whiteandindian = x0060e/x0001e) %>%
  step_mutate(pct_whiteandasian = x0061e/x0001e) %>%
  step_mutate(pct_indianandblack = x0062e/x0001e) %>%
  step_mutate(pc_nothispanic_w = x0077e / x0001e) %>%
  step_mutate(pc_nothispanic_b = x0078e / x0001e) %>%
  step_mutate(pc_nothispanic_i = x0079e / x0001e) %>%
  step_mutate(pc_nothispanic_a = x0080e / x0001e) %>%
  step_mutate(pc_nothispanic_hpi = x0081e / x0001e) %>%
  step_mutate(pc_nothispanic_o = x0082e / x0001e) %>%
  step_mutate(pc_nothispanic_more = x0083e / x0001e) %>%
  step_mutate(pc_nothispanic_more_o = x0084e / x0001e) %>%
  step_mutate(pc_nothispanic_three = x0085e / x0001e) %>%
  step_mutate(pct_lesshighschool_18to24 = c01_002e / ifelse(c01_001e != 0, c01_001e, 1))  %>%
  step_mutate(pct_highschool_18to24 = c01_003e/ifelse(c01_001e != 0, c01_001e, 1)) %>%
  step_mutate(pc_college_18to24 = c01_004e/ifelse(c01_001e != 0, c01_001e, 1)) %>%
  step_mutate(pc_bachelor_18to24 = c01_005e/ifelse(c01_001e != 0, c01_001e, 1)) %>%
  step_mutate(pc_lesshighschool_25over = (c01_007e + c01_008e)/c01_006e) %>%
  step_mutate(pc_highschool_25over = c01_009e/c01_006e) %>%
  step_mutate(pc_college_25over = (c01_010e + c01_011e)/c01_006e) %>%
  step_mutate(pc_bachelorover_25over = c01_015e/c01_006e) %>%
  step_mutate(pc_highschoolover_25over = c01_014e/c01_006e) %>%
  step_mutate(pc_associate_25over = c01_011e / c01_006e ) %>%
  step_mutate(pc_bachlor_25over = c01_012e / c01_006e ) %>%
  step_mutate(pc_graduate_25over = c01_013e / c01_006e ) %>%
  step_mutate(pc_highschool_25to34 = c01_017e/ c01_016e) %>%
  step_mutate(pc_bachelor_25to34 = c01_018e/ c01_016e) %>%
  step_mutate(pc_highschool_35to44 = c01_020e/ c01_019e) %>%
  step_mutate(pc_bachelor_35to44 = c01_021e/ c01_019e) %>%
  step_mutate(pc_highschool_45to64 = c01_023e/ c01_022e) %>%
  step_mutate(pc_bachelor_45to64 = c01_024e/ c01_022e) %>%
  step_mutate(pc_highschool_65over = c01_026e/ c01_025e) %>%
  step_mutate(pc_bachelor_65over = c01_027e/ c01_025e) %>%
  step_mutate(mean_income_per_cap = (income_per_cap_2016 + income_per_cap_2017+ income_per_cap_2018 + income_per_cap_2019+ income_per_cap_2020) / 5)  %>%
  step_mutate(mean_gdp = (gdp_2016+ gdp_2017+ gdp_2018 + gdp_2019+ gdp_2020)/5) %>%
  step_mutate(pc_vote_population = total_votes / x0001e) %>%
  step_mutate(pc_vote_eligible = total_votes/x0087e) %>%
  #step_mutate(housing_unit_per_person = x0086e / x0001e)  %>%
  step_rm(x0002e, x0009e, x0010e, x0003e, x0005e, x0006e, x0007e, x0008e, x0033e, x0011e, x0012e, x0013e, x0014e, x0015e, x0016e, x0017e) %>%
  step_rm(x0020e, x0021e, x0022e, x0023e, x0024e, x0025e, x0029e, x0087e, x0088e, x0089e) %>% #age
  step_rm(x0034e, x0035e, x0036e, x0037e, x0038e, x0039e, x0040e, x0052e, x0044e,x0057e, x0058e, x0064e, x0065e,x0066e, x0067e, x0068e, x0069e, x0071e) %>% #race
  #step_rm(income_per_cap_2016, income_per_cap_2018, income_per_cap_2017, income_per_cap_2019, income_per_cap_2020) %>%
  #step_rm(gdp_2016, gdp_2017, gdp_2018, gdp_2019, gdp_2020) %>%
  step_rm(c01_002e, c01_015e,c01_011e,c01_010e, c01_009e, c01_008e, c01_007e,  c01_005e, c01_004e, c01_003e) %>% 
  step_rm(c01_017e, c01_018e, c01_019e, c01_020e, c01_021e, c01_022e, c01_023e, c01_024e, c01_025e, c01_026e, c01_027e)%>% 
  step_rm(x0041e, x0042e, x0043e, x0045e, x0046e, x0047e, x0048e, x0049e, x0050e, x0051e, x0053e, x0054e, x0055e, x0056e) %>% 
  step_rm(matches("^x007[2-9]e$|^x008[0-5]e$"))  %>%
  step_rm(x0019e, x0026e, x0027e, x0031e, x0030e, x0060e, x0061e, x0062e, x0059e) %>%
  step_rm(c01_001e, c01_006e, c01_012e, c01_013e, c01_016e)%>%
  step_rm(c01_014e)%>%
  step_rm(total_votes) %>%
  #step_rm(x0086e) %>%
 # step_corr(all_predictors(), threshold = 0.99) %>%
  step_num2factor(x2013_code, levels = code2013) %>%
  step_dummy(x2013_code) %>%
  #step_scale(all_predictors()) %>%
 # step_normalize(all_predictors()) %>%
  step_zv(all_predictors())

```

```{r}
set.seed(10)
train_folds <- train %>% vfold_cv(v = 10, strata = 'percent_dem')
```

Random forest: 
```{r}

rf_model <- rand_forest(trees = 500) %>% 
            set_engine("ranger", importance = "impurity")  %>% 
            set_mode("regression")

rf_workflow <- 
  workflow() %>%
  add_recipe(rf_recipe_1) %>%
  add_model(rf_model)

rf_crossval_fit_1 <- 
  rf_workflow %>%
  fit_resamples(train_folds)

rf_crossval_fit_1 %>% 
  collect_metrics()


```

```{r}
rf_fit_3 <- 
  rf_workflow %>%
  fit(data = train)

```

```{r}
fitted_rf_model <- rf_fit_3 %>% extract_fit_parsnip()
## determine important variables
imp <- data.frame(fitted_rf_model$fit$variable.importance)
not_imp_var <- rownames(top_n(imp, -10))
arrange(imp, imp$fitted_rf_model.fit.variable.importance)
rf_recipe_2 <-
 rf_recipe_1 %>%
  step_rm(all_of(not_imp_var))
```

```{r}
rf_test_res_3 <-
  rf_fit_3 %>%
  predict(test) %>%
  cbind(test %>% select(id))


rf_test_res <- 
  rf_test_res_3 %>%
  select(id = id, percent_dem = .pred)
head(rf_test_res)

#write_csv(rf_test_res, "final_predictions_9.csv")


```


Bagged trees via rpart model:  
```{r}
library(baguette)
library(caret)
library(rpart)
```

```{r}
code2013 <- c("one", "two", "three", "four", "five", "six")
## Create a recipe
recipe_2 <- recipe(percent_dem ~ ., data = train) %>%
  step_rm(id) %>%
  step_impute_knn(all_predictors()) %>%
  step_mutate(pct_male = x0002e / x0001e) %>%
  step_mutate(pct_female = x0003e / x0001e) %>%
  step_mutate(pct_male_18over = x0026e / x0001e) %>%
  step_mutate(pct_female_18over = x0027e / x0001e) %>%
  step_mutate(pct_21andover = x0022e / x0001e) %>%
  step_mutate(pct_62andove = x0023e / x0001e) %>%
  step_mutate(pct_female_65over = x0031e / x0001e) %>%
  step_mutate(pct_male_65over = x0030e / x0001e) %>%
  step_mutate(pct_16over = x0020e / x0001e) %>%
  step_mutate(pct_18over = x0025e / x0001e) %>%
  step_mutate(pct_0to19 = (x0005e + x0006e + x0007e + x0008e) / x0001e) %>%
  step_mutate(pct_20to34 = (x0009e + x0010e) / x0001e) %>%
  step_mutate(pct_35to54 = (x0011e + x0012e) / x0001e) %>%
  step_mutate(pct_55to64 = (x0013e + x0014e) / x0001e) %>%
  step_mutate(pct_65andovr = (x0015e + x0016e + x0017e) / x0001e) %>%
  step_mutate(pct_18o_citizen_m = x0088e / x0001e) %>%
  step_mutate(pct_18o_citizen_f = x0089e / x0001e) %>%
  step_mutate(pct_18o_citizen = x0087e / x0001e) %>%
  step_mutate(pct_onerace = x0034e / x0001e) %>%
  step_mutate(pct_morerace = x0035e / x0001e) %>%
  step_mutate(pct_white = x0037e / x0001e) %>%
  step_mutate(pct_black = x0038e / x0001e) %>%
  step_mutate(pct_indian = x0039e / x0001e) %>%
  step_mutate(pct_asian = x0044e / x0001e) %>%
  step_mutate(pct_api = x0052e / x0001e) %>%
  step_mutate(pct_otherrace = x0057e / x0001e) %>%
  step_mutate(pct_white_c = x0064e / x0001e) %>%
  step_mutate(pct_black_c = x0065e / x0001e) %>%
  step_mutate(pct_indian_c = x0066e / x0001e) %>%
  step_mutate(pct_asian_c = x0067e / x0001e) %>%
  step_mutate(pct_api_c = x0068e / x0001e) %>%
  step_mutate(pct_other_c = x0069e / x0001e) %>%
  step_mutate(pct_his = x0071e / x0001e) %>%
  step_mutate(pct_cherokee = x0040e / x0001e) %>%
  step_mutate(pct_chippewa = x0041e / x0001e) %>%
  step_mutate(pct_navajo = x0042e / x0001e) %>%
  step_mutate(pct_sioux = x0043e / x0001e) %>%
  step_mutate(pct_indian = x0045e / x0001e) %>%
  step_mutate(pct_chinese = x0046e / x0001e) %>%
  step_mutate(pct_filipino = x0047e / x0001e) %>%
  step_mutate(pct_japanese = x0048e / x0001e) %>%
  step_mutate(pct_korean = x0049e / x0001e) %>%
  step_mutate(pct_viet = x0050e / x0001e) %>%
  step_mutate(pct_othera = x0051e / x0001e) %>%
  step_mutate(pct_hawaii = x0053e / x0001e) %>%
  step_mutate(pct_chamorro = x0054e / x0001e) %>%
  step_mutate(pct_samoan = x0055e / x0001e) %>%
  step_mutate(pct_otherpi = x0056e / x0001e) %>%
  step_mutate(pct_mexican = x0072e / x0001e) %>%
  step_mutate(pct_puertorican = x0073e / x0001e) %>%
  step_mutate(pct_cuban = x0074e / x0001e) %>%
  step_mutate(pct_otherh = x0075e / x0001e) %>%
  step_mutate(pct_whiteandblack = x0059e / x0001e) %>%
  step_mutate(pct_whiteandindian = x0060e / x0001e) %>%
  step_mutate(pct_whiteandasian = x0061e / x0001e) %>%
  step_mutate(pct_indianandblack = x0062e / x0001e) %>%
  step_mutate(pc_nothispanic_w = x0077e / x0001e) %>%
  step_mutate(pc_nothispanic_b = x0078e / x0001e) %>%
  step_mutate(pc_nothispanic_i = x0079e / x0001e) %>%
  step_mutate(pc_nothispanic_a = x0080e / x0001e) %>%
  step_mutate(pc_nothispanic_hpi = x0081e / x0001e) %>%
  step_mutate(pc_nothispanic_o = x0082e / x0001e) %>%
  step_mutate(pc_nothispanic_more = x0083e / x0001e) %>%
  step_mutate(pc_nothispanic_more_o = x0084e / x0001e) %>%
  step_mutate(pc_nothispanic_three = x0085e / x0001e) %>%
  step_mutate(pct_lesshighschool_18to24 = c01_002e / ifelse(c01_001e != 0, c01_001e, 1)) %>%
  step_mutate(pct_highschool_18to24 = c01_003e / ifelse(c01_001e != 0, c01_001e, 1)) %>%
  step_mutate(pc_college_18to24 = c01_004e / ifelse(c01_001e != 0, c01_001e, 1)) %>%
  step_mutate(pc_bachelor_18to24 = c01_005e / ifelse(c01_001e != 0, c01_001e, 1)) %>%
  step_mutate(pc_lesshighschool_25over = (c01_007e + c01_008e) / c01_006e) %>%
  step_mutate(pc_highschool_25over = c01_009e / c01_006e) %>%
  step_mutate(pc_college_25over = (c01_010e + c01_011e) / c01_006e) %>%
  step_mutate(pc_bachelorover_25over = c01_015e / c01_006e) %>%
  step_mutate(pc_highschoolover_25over = c01_014e / c01_006e) %>%
  step_mutate(pc_associate_25over = c01_011e / c01_006e) %>%
  step_mutate(pc_bachlor_25over = c01_012e / c01_006e) %>%
  step_mutate(pc_graduate_25over = c01_013e / c01_006e) %>%
  step_mutate(pc_highschool_25to34 = c01_017e / c01_016e) %>%
  step_mutate(pc_bachelor_25to34 = c01_018e / c01_016e) %>%
  step_mutate(pc_highschool_35to44 = c01_020e / c01_019e) %>%
  step_mutate(pc_bachelor_35to44 = c01_021e / c01_019e) %>%
  step_mutate(pc_highschool_45to64 = c01_023e / c01_022e) %>%
  step_mutate(pc_bachelor_45to64 = c01_024e / c01_022e) %>%
  step_mutate(pc_highschool_65over = c01_026e / c01_025e) %>%
  step_mutate(pc_bachelor_65over = c01_027e / c01_025e) %>%
  step_mutate(mean_income_per_cap = (income_per_cap_2016 + income_per_cap_2017 + income_per_cap_2018 + income_per_cap_2019 + income_per_cap_2020) / 5) %>%
  step_mutate(mean_gdp = (gdp_2016 + gdp_2017 + gdp_2018 + gdp_2019 + gdp_2020) / 5) %>%
  step_mutate(pc_vote_population = total_votes / x0001e) %>%
  step_mutate(pc_vote_eligible = total_votes / x0087e) %>%
  step_rm(
    x0002e, x0009e, x0010e, x0003e, x0005e, x0006e, x0007e, x0008e, x0033e, x0011e,
    x0012e, x0013e, x0014e, x0015e, x0016e, x0017e,
    x0020e, x0021e, x0022e, x0023e, x0024e, x0025e, x0029e, x0087e, x0088e, x0089e
  ) %>%
  step_rm(matches("^x007[2-9]e$|^x008[0-5]e$")) %>%
  step_rm(x0019e, x0026e, x0027e, x0031e, x0030e, x0060e, x0061e, x0062e, x0059e) %>%
  step_rm(c01_001e, c01_006e, c01_012e, c01_013e, c01_016e) %>%
  step_rm(c01_014e) %>%
  step_rm(total_votes) %>%
  step_zv(all_predictors())
```

```{r}
set.seed(10)
train_folds <- train %>% vfold_cv(v = 10, strata = 'percent_dem')
```

Bagged Trees model:
```{r}
# Create a Bagged Trees model

## Define a bagged model
bagged_model <- bag_tree(
  tree_depth = 25,       # default Maximum tree depth
  min_n = 2,            # default Minimum number of observations in a leaf node
  cost_complexity = 0.01  # Cost complexity parameter
) %>% 
  set_engine("rpart") %>% 
  set_mode("regression")

#create a workflow
bagged_workflow <- 
  workflow() %>%
  add_recipe(recipe_2) %>%
  add_model(bagged_model)

## Fit the bagged model using cross-validation
bagged_crossval_fit_1 <- 
  bagged_workflow %>%
  fit_resamples(train_folds)

## Collect metrics from cross-validation
bagged_crossval_fit_1 %>% 
  collect_metrics()
```
Cubist rule-based regression models:
```{r}
library(Cubist)
library(rules)
```

```{r}
## Define a cubist rules model 
cubist_rules_model <- 
  cubist_rules(committees = 100, max_rules = 500) %>%
  set_engine("Cubist") %>%
  set_mode("regression")

#create a workflow
cubist_workflow <- 
  workflow() %>%
  add_recipe(recipe_2) %>%
  add_model(cubist_rules_model)

## Fit the bagged model using cross-validation
cubist_crossval_fit_1 <- 
  cubist_workflow %>%
  fit_resamples(train_folds)

## Collect metrics from cross-validation
cubist_crossval_fit_1 %>% 
  collect_metrics()
```
tuning grid:
```{r}
cubist_rules_spec <-
  cubist_rules(committees = tune(), neighbors = tune()) %>%
  set_engine("Cubist") %>%
  set_mode("regression") 

# Define a tuning grid
grid <- expand.grid(
  committees = seq(1, 30, by = 1), 
  neighbors = seq(0, 9, by = 1)
)
```

```{r}
# Define a workflow
cubist_workflow_tune <- 
  workflow() %>% 
  add_recipe(recipe_2) %>%
  add_model(cubist_rules_spec)

# Run the tuning grid
cubist_tune_results <- 
  tune_grid(
    cubist_workflow_tune,
    resamples = train_folds,
    grid = grid
    )

# View the tuning results
print(cubist_tune_results)
```


```{r}
test <- read_csv("test.csv")

set.seed(1)
cubist_fit_1 <- 
  cubist_workflow %>%
  fit(data = train)

cubist_test_res_1 <-
  cubist_fit_1 %>%
  predict(new_data = test) %>%
  cbind(test %>% select(id))

cubist_test_res <- 
  cubist_test_res_1 %>%
  select(id = id, percent_dem = .pred)
head(cubist_test_res)

write_csv(cubist_test_res, "final_predictions_10.csv")
```