---
title: "Stats101C_regression_project"
output: pdf_document
date: "2023-09-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load the tidyverse and tidymodels:

```{r}
library(knitr)
library(tidyverse)
library(tidymodels)
library(caret)
library(recipes)
```

```{r}
train <- read.csv("train.csv")
head(train)

test <- read.csv("test.csv")
head(test)

```

Way 1:

```{r}
rf_recipe <-
recipe(percent_dem ~ ., data = train) %>% 
  step_rm(id) %>% 
  step_impute_mean(all_predictors())

print(rf_recipe)
```

```{r}
# Remove non-numeric columns ("name" and "id") and handle missing values
numeric_vars <- train[, !names(train) %in% c("name", "id")]
numeric_vars <- na.omit(numeric_vars)  # Remove rows with missing values

# Calculate the correlation matrix for numeric variables
correlation_matrix <- cor(numeric_vars)

# Identify highly correlated variables
highly_correlated <- findCorrelation(correlation_matrix, cutoff = 0.7)

# Remove correlated variables
train_filtered <- numeric_vars[, -highly_correlated]
train_filtered
```

Way 2:

```{r, error = TRUE}
recipe_obj <- recipe(percent_dem ~ ., data = train) %>%
  step_rm(name, id)
recipe_obj <- recipe_obj %>%
  step_scale(all_predictors())  # Scale all numeric predictors

prepared_data <- prep(recipe_obj)
prepared_data
```

Way 3: output similar to way 4

```{r}
competition_recipe <- recipe(percent_dem ~ ., 
                         data = train) %>%
  step_rm(id) %>%
  step_corr(all_numeric(), threshold = 0.9) %>%
  step_normalize(all_numeric()) %>%
  step_dummy(all_nominal(), -all_outcomes())
competition_recipe

competition_recipe_obj <- competition_recipe %>%
  step_scale(all_predictors())

competition_recipe_prep <- competition_recipe_obj %>%
  prep(training = train)
competition_recipe_prep

competition_training_prep <- competition_recipe_prep %>%
  bake(new_data = NULL)
competition_training_prep

```

Way 4: output similar to way 3

```{r}
train <- train[, -which(names(train) == c("id"))]
head(train)

train %>%
  select_if(is.numeric) %>%
  cor()

competition_cor_rec <- recipe(percent_dem ~ .,
                        data = train) %>%
  step_corr(all_numeric(), threshold = 0.9)
competition_cor_rec

competition_cor_rec %>%
  prep(training = train) %>%
  bake(new_data = NULL)

competition_norm_rec <- recipe(percent_dem ~ ., 
                         data = train) %>%
  step_corr(all_numeric(), threshold = 0.9) %>%
  step_normalize(all_numeric())
competition_norm_rec

competition_norm_rec %>%
  prep(training = train) %>%
  bake(new_data = NULL)
```

Way 5：

```{r}
competition_log_rec <- recipe(percent_dem ~ .,
                        data = train) %>%
  step_log(total_votes, base = 10)
competition_log_rec

competition_log_rec %>%
  summary()

competition_log_rec_prep <- competition_log_rec %>%
  prep(training = train)
competition_log_rec_prep

competition_log_rec_prep %>%
  bake(new_data = NULL)

```
